unit ExchForm;

interface

const

 EXCHIVERB_OPEN              = 0;
 EXCHIVERB_RESERVED_COMPOSE  = 100;
 EXCHIVERB_RESERVED_OPEN     = 101;
 EXCHIVERB_REPLYTOSENDER     = 102;
 EXCHIVERB_REPLYTOALL        = 103;
 EXCHIVERB_FORWARD           = 104;
 EXCHIVERB_PRINT             = 105;
 EXCHIVERB_SAVEAS            = 106;
 EXCHIVERB_RESERVED_DELIVERY = 107;
 EXCHIVERB_REPLYTOFOLDER     = 108;


implementation

end.
 