{++

  m a p i h o o k . p a s

  Abstract:

    Automatic conversion of mapihook.h.

  Comments:

    This source file automatically converted by
    htrans 0.91 beta 1 Copyright (c) 1997 Alexander Staubo

  Revision history:

    18-06-1997 20:53 alex  [Autogenerated]
    18-06-1997 20:53 alex  Retouched for release

--}

unit MapiHook;

{$A+}
{$MINENUMSIZE 4}

interface

uses
  Windows, SysUtils, ActiveX,
  MapiDefs, MapiX, MapiGuid;

(*
 *  M A P I H O O K . H
 *
 *  Defines the SpoolerMsgHook provider interface.
 *
 *  Copyright 1986-1996 Microsoft Corporation. All Rights Reserved.
 *)

{ ISpoolerHook Interface ------------------------------------------------ }

{ MsgHooks }

const
  HOOK_DELETE = ULONG($00000001);
  HOOK_CANCEL = ULONG($00000002);

type
  ISpoolerHook =
    interface(IUnknown)
    [strIID_ISpoolerHook]
      function QueryInterface (riid : PIID; var ppvObj : Pointer) : HResult; stdcall;
      function AddRef : ULONG; stdcall;
      function Release : ULONG; stdcall;
      function InboundMsgHook (lpMessage : IMessage; lpFolder : IMAPIFolder; 
        lpMDB : IMsgStore; var lpulFlags : ULONG; var lpcbEntryID : ULONG; 
        var lppEntryID : PBYTE) : HResult; stdcall;
      function OutboundMsgHook (lpMessage : IMessage; lpFolder : IMAPIFolder; 
        lpMDB : IMsgStore; var lpulFlags : ULONG; var lpcbEntryID : ULONG; 
        var lppEntryID : PBYTE) : HResult; stdcall;
    end;
  
  {!! htrans: [MAPI DECLARE_MAPI_INTERFACE_PTR macro] }
  
{ Hook Provider Entry Point }

const
  HOOK_INBOUND = ULONG($00000200);
  HOOK_OUTBOUND = ULONG($00000400);

{!! Note: Message hook providers export a function called "HPProviderInit"
  following the syntax of this function declaration }

type
  THPPROVIDERINIT = function (lpSession : IMAPISession; hInstance : HINST;
    lpAllocateBuffer : PALLOCATEBUFFER; lpAllocateMore : PALLOCATEMORE;
    lpFreeBuffer : PFREEBUFFER; lpSectionUID : PMAPIUID; ulFlags : ULONG;
    out lppSpoolerHook : ISpoolerHook) : HResult; cdecl;

implementation

end.

