{++

  m a p i w z . p a s

  Abstract:

    Automatic conversion of mapiwz.h.

  Comments:

    This source file automatically converted by
    htrans 0.91 beta 1 Copyright (c) 1997 Alexander Staubo

  Revision history:

    18-06-1997 20:53 alex  [Autogenerated]
    18-06-1997 20:53 alex  Retouched for release

--}

unit MapiWz;

{$A+}
{$MINENUMSIZE 4}

interface

uses
  Windows, SysUtils, ActiveX, Messages,
  MapiDefs;

(*
 *  M A P I W Z . H
 *
 *  Definitions for the Profile Wizard.  Includes all prototypes
 *  and constants required by the provider-wizard code consumers.
 *
 *  Copyright 1986-1996 Microsoft Corporation. All Rights Reserved.
 *)

const
  WIZ_QUERYNUMPAGES = (WM_USER + 10);
  WIZ_NEXT = (WM_USER + 11);
  WIZ_PREV = (WM_USER + 12);

(*
 *  NOTE: Provider-Wizards should not use ids ranging between
 *  (WM_USER + 1) and (WM_USER +20) as these have been reserved for 
 *  future releases.
 *)

{  Flags for LaunchWizard API }

const
  MAPI_PW_FIRST_PROFILE = $00000001;
  MAPI_PW_LAUNCHED_BY_CONFIG = $00000002;
  MAPI_PW_ADD_SERVICE_ONLY = $00000004;
  MAPI_PW_PROVIDER_UI_ONLY = $00000008;
  MAPI_PW_HIDE_SERVICES_LIST = $00000010;

(*
 *  Provider should set this property to TRUE if it does not
 *  want the Profile Wizard to display the PST setup page.
 *)

const
  PR_WIZARD_NO_PST_PAGE = (PT_BOOLEAN) or (($6700) shl 16);

type
  TLAUNCHWIZARDENTRY = function (hParentWnd : HWND; ulFlags : ULONG;
    var lppszServiceNameToAdd : PAnsiChar; cbBufferMax : ULONG;
    lpszNewProfileName : PAnsiChar) : HResult; stdcall;

  PLAUNCHWIZARDENTRY = ^TLAUNCHWIZARDENTRY;

  TSERVICEWIZARDDLGPROC = function (hDlg : HWND; wMsgID : UINT; wParam : WPARAM;
    lParam : LPARAM) : BOOL; stdcall;

  PSERVICEWIZARDDLGPROC = ^TSERVICEWIZARDDLGPROC;

  TWIZARDENTRY = function (hProviderDLLInstance : HINST;
    var lppcsResourceName : PAnsiChar; var lppDlgProc : TFNDlgProc;
    lpMapiProp : IMapiProp; lpMapiSupportObject : Pointer) : ULONG; stdcall;

  PWIZARDENTRY = ^TWIZARDENTRY;

const
  LAUNCHWIZARDENTRYNAME = 'LAUNCHWIZARD';

implementation

end.

