echo j|del  ..\source\base\lib
echo j|del  ..\source\base\dbintfs\lib
echo j|del  ..\source\promet.erp\lib
echo j|del  ..\source\tools\lib
echo j|del  ..\source\projectcmanagement\lib
echo j|del  ..\source\clientmanagement\lib
echo j|del  ..\source\messageimport\lib
echo j|del  ..\source\archivestore\lib
echo j|del  ..\source\base_calendar\lib
echo j|del  ..\source\base_documents\lib
echo j|del  ..\source\base_calendar\lib
echo j|del  ..\source\base_erp\lib
echo j|del  ..\source\base_messaging\lib
echo j|del  ..\source\base_ocr\lib
echo j|del  ..\source\base_office\lib
echo j|del  ..\source\base_phone\lib
echo j|del  ..\source\base_pm\lib
echo j|del  ..\source\base_repair\lib
echo j|del  ..\source\base_wiki\lib
echo j|del  ..\source\checkout\lib
echo j|del  ..\source\httpserver\lib
echo j|del  ..\source\import\lib
echo j|del  ..\source\nntpserver\lib
echo j|del  ..\source\pos\lib
echo j|del  ..\source\statistics\lib
echo j|del  ..\source\svnserver\lib
echo j|del  ..\source\sync\lib
echo j|del  ..\source\timeregistering\lib
echo j|del  ..\source\tools\lib
