#!/bin/bash
rm -f -r ../source/base/lib
rm -f -r ../source/base/dbintfs/lib
rm -f -r ../source/promet.erp/lib
rm -f -r ../source/tools/lib
rm -f -r ../source/projectcmanagement/lib
rm -f -r ../source/clientmanagement/lib
rm -f -r ../source/messageimport/lib
rm -f -r ../source/archivestore/lib
rm -f -r ../source/base_calendar/lib
rm -f -r ../source/base_documents/lib
rm -f -r ../source/base_calendar/lib
rm -f -r ../source/base_erp/lib
rm -f -r ../source/base_messaging/lib
rm -f -r ../source/base_ocr/lib
rm -f -r ../source/base_office/lib
rm -f -r ../source/base_phone/lib
rm -f -r ../source/base_pm/lib
rm -f -r ../source/base_repair/lib
rm -f -r ../source/base_wiki/lib
rm -f -r ../source/checkout/lib
rm -f -r ../source/httpserver/lib
rm -f -r ../source/import/lib
rm -f -r ../source/nntpserver/lib
rm -f -r ../source/pos/lib
rm -f -r ../source/statistics/lib
rm -f -r ../source/svnserver/lib
rm -f -r ../source/sync/lib
rm -f -r ../source/timeregistering/lib
rm -f -r ../source/tools/lib

